### ISSUE TITLE
Copying landfill causes a non-recoverable error

### ISSUE THREAD

**Issue by RigSaw31** [raiguard/Factorio-TrainGroups#3] opened 2022-04-14 17:23 UTC
#### Describe the Bug
Copying landfill causes a non-recoverable error
(screen shot) https://gyazo.com/5c5381578e46e5410dec930b079436ec
#### To Reproduce
copy area of landfill 

#### Save file & Username
(Name) Rig_saw_31
(world file)  https://www.mediafire.com/file/b625eckgrirktaj/_autosave1.zip/file
Note: This is a multiplayer world that I host locally 
(mods)  https://www.mediafire.com/file/a8mfh6wywy801ab/mods.zip/file

#### Log file
[factorio-current.log](https://github.com/raiguard/Factorio-TrainGroups/files/8491077/factorio-current.log)
[factorio-previous.log](https://github.com/raiguard/Factorio-TrainGroups/files/8491078/factorio-previous.log)

## If I have made any mistakes in this report please let me know. Thank you for working on this mod and I hope this helps.

**Comment by raiguard** [comment] 2022-04-14 17:34
Thanks for the report, however, this bug was already fixed. Please update the mod to 1.0.1.

Duplicate of #2

**Closed by raiguard** 2022-04-14 17:34 UTC
Labels: bug
